In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split, cross_val_score

from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
machine_data = pd.read_csv(r"E:\360digiTMG-Project\processed_file.csv",index_col = 0)

machine = machine_data.copy()

In [4]:
machine.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2289 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Date                         2289 non-null   object 
 1   Machine_ID                   2289 non-null   object 
 2   Hydraulic_Pressure           2289 non-null   float64
 3   Coolant_Pressure             2289 non-null   float64
 4   Air_System_Pressure          2289 non-null   float64
 5   Coolant_Temperature          2289 non-null   float64
 6   Hydraulic_Oil_Temperature    2289 non-null   float64
 7   Spindle_Bearing_Temperature  2289 non-null   float64
 8   Spindle_Vibration            2289 non-null   float64
 9   Tool_Vibration               2289 non-null   float64
 10  Spindle_Speed                2289 non-null   float64
 11  Voltage                      2289 non-null   float64
 12  Torque                       2289 non-null   float64
 13  Cutting                

In [5]:
machine.Downtime.head()
machine.Downtime.tail()

2494    No_Machine_Failure
2495    No_Machine_Failure
2496    No_Machine_Failure
2498    No_Machine_Failure
2499       Machine_Failure
Name: Downtime, dtype: object

In [6]:
machine["Downtime"] = machine["Downtime"].map({"Machine_Failure":0,"No_Machine_Failure":1})

machine = pd.get_dummies(machine,drop_first = True)

columns = list(machine.columns)

features = list(set(columns) - set(['Downtime']))

print(features)


['Date_01-03-2022', 'Date_29-03-2022', 'Date_05-01-2022', 'Date_06-03-2022', 'Date_28-03-2022', 'Date_12-04-2022', 'Date_19-03-2022', 'Date_21-12-2021', 'Date_25-02-2022', 'Torque', 'Date_17-04-2022', 'Date_27-02-2022', 'Date_22-01-2022', 'Date_25-05-2022', 'Date_15-02-2022', 'Date_30-12-2021', 'Date_12-03-2022', 'Hydraulic_Pressure', 'Date_09-05-2022', 'Date_23-05-2022', 'Date_03-04-2022', 'Date_08-05-2022', 'Date_06-01-2022', 'Tool_Vibration', 'Date_01-05-2022', 'Date_28-01-2022', 'Date_09-04-2022', 'Date_08-04-2022', 'Date_02-05-2022', 'Date_26-03-2022', 'Date_08-03-2022', 'Date_16-05-2022', 'Date_13-02-2022', 'Date_19-06-2022', 'Date_13-03-2022', 'Date_02-04-2022', 'Date_04-05-2022', 'Date_20-03-2022', 'Date_20-01-2022', 'Coolant_Temperature', 'Date_10-04-2022', 'Date_24-05-2022', 'Date_09-03-2022', 'Date_22-03-2022', 'Date_02-02-2022', 'Date_17-12-2021', 'Date_08-02-2022', 'Date_04-03-2022', 'Date_31-12-2021', 'Machine_ID_Makino-L3-Unit1-2015', 'Date_24-02-2022', 'Date_10-05-2022'

In [7]:
print(columns)

['Hydraulic_Pressure', 'Coolant_Pressure', 'Air_System_Pressure', 'Coolant_Temperature', 'Hydraulic_Oil_Temperature', 'Spindle_Bearing_Temperature', 'Spindle_Vibration', 'Tool_Vibration', 'Spindle_Speed', 'Voltage', 'Torque', 'Cutting', 'Downtime', 'Date_01-03-2022', 'Date_01-04-2022', 'Date_01-05-2022', 'Date_02-02-2022', 'Date_02-03-2022', 'Date_02-04-2022', 'Date_02-05-2022', 'Date_03-01-2022', 'Date_03-02-2022', 'Date_03-03-2022', 'Date_03-04-2022', 'Date_03-05-2022', 'Date_04-02-2022', 'Date_04-03-2022', 'Date_04-04-2022', 'Date_04-05-2022', 'Date_04-06-2022', 'Date_05-01-2022', 'Date_05-02-2022', 'Date_05-03-2022', 'Date_05-04-2022', 'Date_05-05-2022', 'Date_06-01-2022', 'Date_06-02-2022', 'Date_06-03-2022', 'Date_06-04-2022', 'Date_06-05-2022', 'Date_06-06-2022', 'Date_07-01-2022', 'Date_07-02-2022', 'Date_07-03-2022', 'Date_07-04-2022', 'Date_07-05-2022', 'Date_07-06-2022', 'Date_08-01-2022', 'Date_08-02-2022', 'Date_08-03-2022', 'Date_08-04-2022', 'Date_08-05-2022', 'Date_08-1

In [8]:
machine.head()

Hydraulic_Pressure  Coolant_Pressure  Air_System_Pressure  \
0               71.04          6.933725             6.284965   
1              125.33          4.936892             6.196733   
2               71.12          6.839413             6.655448   
3              139.34          4.574382             6.560394   
4               60.51          6.893182             6.141238   

   Coolant_Temperature  Hydraulic_Oil_Temperature  \
0                 25.6                       46.0   
1                 35.3                       47.4   
2                 13.1                       40.7   
3                 24.4                       44.2   
4                  4.1                       47.3   

   Spindle_Bearing_Temperature  Spindle_Vibration  Tool_Vibration  \
0                         33.4              1.291          26.492   
1                         34.6              1.382          25.274   
2                         33.0              1.319          30.608   
3                         40.6              0.618          30.791   
4                         31.4              0.983          25.516   

   Spindle_Speed  Voltage  ...  Date_30-01-2022  Date_30-03-2022  \
0        25892.0    335.0  ...            False            False   
1        19856.0    368.0  ...            False            False   
2        19851.0    325.0  ...            False            False   
3        18461.0    360.0  ...            False            False   
4        26526.0    354.0  ...            False            False   

   Date_30-04-2022  Date_30-12-2021  Date_31-01-2022  Date_31-03-2022  \
0            False            False            False            False   
1            False            False            False            False   
2            False            False            False            False   
3            False            False            False            False   
4            False            False            False             True   

   Date_31-05-2022  Date_31-12-2021  Machine_ID_Makino-L2-Unit1-2015  \
0            False             True                            False   
1            False             True                            False   
2            False             True                            False   
3             True            False                             True   
4            False            False                            False   

   Machine_ID_Makino-L3-Unit1-2015  
0                            False  
1                            False  
2                             True  
3                            False  
4                            False  

[5 rows x 175 columns]

In [9]:
x = machine[features].values
print(x)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


In [10]:
y = machine['Downtime'].values
print(y)

[0 0 0 ... 1 1 0]


In [11]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size = 0.20)

print(train_x.shape,test_x.shape,train_y.shape,test_y.shape)

(1831, 174) (458, 174) (1831,) (458,)


In [12]:
#Model Building

from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

logistic_model.fit(train_x,train_y)

logistic_predictions = logistic_model.predict(test_x)

C:\Users\vishn\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
# confusion matrix - Logistic Regression

confusion = confusion_matrix(test_y,logistic_predictions)

print(confusion)

# Finding accuracy
accuracy = accuracy_score(test_y,logistic_predictions)

print(accuracy)

[[188  51]
 [ 41 178]]
0.7991266375545851


In [14]:
# Decision Tree model 

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()

dt_model.fit(train_x,train_y)

dt_predictions = dt_model.predict(test_x)

In [16]:
#Confusion matrix - Decision Tree

dt_confusion = confusion_matrix(test_y,dt_predictions)

print(dt_confusion)

#Accuracy

dt_accuracy = accuracy_score(test_y,dt_predictions)

print(dt_accuracy)

[[231   8]
 [  3 216]]
0.9759825327510917


In [20]:
# Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()

rf_model.fit(train_x,train_y)

rf_predictions = rf_model.predict(test_x)


In [21]:
# Confusion Matrix - Random Forest

rf_confusion = confusion_matrix(test_y,rf_predictions)

print(rf_confusion)

# Accuracy - Random Forest

rf_accuracy = accuracy_score(test_y,rf_predictions)

print(rf_accuracy)

[[234   5]
 [  3 216]]
0.982532751091703


In [24]:
# KNN - Classifier

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors = 3)

knn_model.fit(train_x,train_y)

print(test_x)

knn_predictions = knn_model.predict(test_x)

print(knn_predictions)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


AttributeError: 'NoneType' object has no attribute 'split'

In [29]:
# SVM

from sklearn.svm import SVC

svc_model = SVC()

svc_model.fit(train_x,train_y)

svc_predictions = svc_model.predict(test_x)


In [30]:
# Metrics for SVM

# Confusion Matrix
svc_confusion = confusion_matrix(test_y,svc_predictions)
print(svc_confusion)

# Accuracy
svc_accuracy = accuracy_score(test_y,svc_predictions)
print(svc_accuracy)


[[ 77 162]
 [  8 211]]
0.62882096069869


In [33]:
# Naive Bayers 

from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()

nb_model.fit(train_x,train_y)

nb_predictions = nb_model.predict(test_x)

In [35]:
# Metrics for Naive Bayes Algorithm

#Confusion Matrix
nb_confusion = confusion_matrix(test_y,nb_predictions)
print(nb_confusion)

#Accuracy
nb_accuracy = accuracy_score(test_y,nb_predictions)
print(nb_accuracy)

[[158  81]
 [ 68 151]]
0.6746724890829694
